### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by GotEmB** [Qard/express-coffee#5]
How am I supposed to view the log data form express-coffee?

**Comment by Qard** [comment]
express-coffee has largely been replaced by a newer module of mine called [crsh](https://github.com/Qard/crsh). I'd recommend giving that a try instead.

**Comment by elisee** [comment]
For what it's worth, you can view the log data by passing debug: true as an option.

**Comment by GotEmB** [comment]
k.. thanks!
